# Generated by Django 4.2.2 on 2023-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Educational", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educational",
            name="url",
            field=models.URLField(),
        ),
    ]
