# Generated by Django 4.2.2 on 2023-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Educational", "0002_alter_educational_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educational",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
